@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTczNDI2NDh9.O0iYYMZFKSr9-hrXfW8MKxs09adP_p3-QaRwCulgWPE
### Media Index
GET http://localhost:3000/media.json

### Media Show
GET http://localhost:3000/media/1.json

### Media Destroy
DELETE http://localhost:3000/media/10.json
Authorization: Bearer {{ jwt }}