@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTczMDU2NTB9.QRuIy_gHNDqP5V6M09eKl5y-UfMpnbSQSZCTrpHVpMI

### trackers Index
GET http://localhost:3000/trackers.json
Authorization: Bearer {{ jwt }}

### trackers Create
POST http://localhost:3000/trackers.json
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "medium_id": 1,
  "current": 34,
  "progress": "Watching"
}

### trackers Update
PATCH http://localhost:3000/trackers/2.json
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "user_id": 1,
  "medium_id":4,
  "current": 111,
  "progress": "Test 2"
}
### trackers Destroy
DELETE http://localhost:3000/trackers/3.json
Authorization: Bearer {{ jwt }}
