@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTcyMTIzNjZ9.2eC7VRv6Xz_1VpcqO6emAx1qfFWnJymG7tsHpKa3UuQ

### trackers Index
GET http://localhost:3000/trackers.json

### Medium Create
POST http://localhost:3000/trackers.json
Content-Type: application/json
# Authorization: Bearer {{ jwt }}

{
  "user_id": 1,
  "medium_id": 3,
  "current": 121,
  "progress": "Test"
}

### trackers Show
GET http://localhost:3000/trackers/1.json

### trackers Update
PATCH http://localhost:3000/trackers/2.json
Content-Type: application/json

{
  "user_id": 1,
  "medium_id":4,
  "current": 111,
  "progress": "Test 2"
}
### trackers Destroy
DELETE http://localhost:3000/trackers/3.json